Terumo Partdev/src/objects/Account_Share_Log__c.object
<CustomObject>
    <description>nsebastian 11/6/2015: This is a setup object to log details of when an Account is shared, to run a batch to delete the record on expiry.</description>
    <fields>
        <fullName>AccountShareID__c</fullName>
        <description>nsebastian 11/6/2015 : Id of the Account Share record.</description>
        <label>AccountShareID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <description>nsebastian 11/6/2015 : The date of expiry for the record.</description>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>nsebastian 11/12/2015: This field indicates which corresponding AccountShare records were processed by the batch job</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Share Log</label>
    <nameField>
        <displayFormat>ASLOG-{000000}</displayFormat>
        <label>Account Share Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Share Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Terumo Partdev/src/classes/BatchRevokeAccountSharing.cls
/************************************************************************
 * Name  : BatchRevokeAccountSharing
 * Author : Deloitte Consulting
 * Desc  : This batch class checks for Account sharing expiry and deletes the sharing records
 *
 * Modification Log:
 * ----------------------------------------------------------------------
 * Developer                    Date            Description
 * ----------------------------------------------------------------------
 * NSebastian@Deloitte         11/10/2015             Original Version
 * 
 *************************************************************************/
 global class BatchRevokeAccountSharing implements Database.Batchable<SObject>{
        private Date thisdate;
        private String pendingStatus = 'Pending';
        private String processedStatus = 'Processed';
        global BatchRevokeAccountSharing(){
                   // Batch Constructor
                   thisdate = System.today();
        }
       
        // Start Method
        global Database.QueryLocator start(Database.BatchableContext BC){
          //String query = 'SELECT Id FROM AccountShare WHERE Id IN (SELECT AccountShareID__c FROM Account_Share_Log__c WHERE Expiry_Date__c =:System.today()) LIMIT 200';
        	//Date thisdate = System.today();
          String query = 'SELECT AccountShareID__c FROM Account_Share_Log__c WHERE Expiry_Date__c = :thisdate AND Status__c = :pendingStatus';
          return Database.getQueryLocator(query);
        }
      
      // Execute Logic
       global void execute(Database.BatchableContext BC, List<Account_Share_Log__c> scope){
              // Logic to be Executed batch wise 
              List<AccountShare> accountShareList = new List<AccountShare>();
              for(Account_Share_Log__c log: scope) {
                accountShareList.add(new AccountShare(Id= log.AccountShareID__c));
                log.Status__c = processedStatus;
              }
              Database.delete(accountShareList); 
              Database.update(scope);

     
       }
     
       global void finish(Database.BatchableContext BC){
            // Logic to be Executed at finish
            
       }
    }